spring:
  datasource:
#    url: jdbc:postgresql://localhost:5454/countries_dev
    url: jdbc:oracle:thin:@//localhost:1521/HOSSEINTESTDB
    username: USERDATA
    password: hossein
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
cache:
  config:
    entryTtl: 60
    userInfo:
      entryTtl: 30